### ISSUE TITLE
Dogechain rap song

### ISSUE THREAD

**Issue by saferugdev** [dogechain-lab/dogechain#130]
### Description

Hey guys, i know this is totally the wrong place to ask for this, but theres a guy creating crypto themed rap songs, and he has covered more than 100 projects. Could you go ask the team if they are interested in a dodgechain rapsong?

### Your environment

Dogechain 4.2.0 or higher

### Expected behaviour

Grow community trust and support by providing something of great cultural value.

**Comment by DarianShawn** [comment]
Thanks for your advice.
You could go to the discord channel or official telegram.
Issue is only for tech discussion.
