### ISSUE TITLE
Snapshot dogechain???

### ISSUE THREAD

**Issue by ruanling** [dogechain-lab/dogechain#133]
Do you have the latest snapshot?
Syncing from the beginning is too long

**Comment by fomotrader** [comment]
did you manage to find a snapshot?

**Comment by null-void-zero** [comment]
How do you sync from the beginning? The documentation (https://docs.dogechain.dog/docs/overview) is for setting up your own Polygon Edge network

**Comment by fomotrader** [comment]
I'm trying to figure it out by experimenting but it's kind of hard and I've had no luck so far, I think ruanling got further then us

**Comment by null-void-zero** [comment]
@fomotrader refer to this tweet: https://twitter.com/DogechainFamily/status/1559610335367073792
they're:
> preparing Genesis and node deployment base for the community and ecosystem projects to build your own node.

**Comment by ruanling** [comment]
I'm running, but syncing from the beginning will take a long time, I run 12 hours to block 21938, while the current block is 900,000

![image](https://user-images.githubusercontent.com/33116879/185042416-a4e3cd24-65b7-4b9b-a872-89655a240c1f.png)

**Comment by null-void-zero** [comment]
@ruanling what are the specs on your server and how fast is your connection? That seems slow, I can sync all of bsc in 12 hours. How were you able to start the sync in the first place?

**Comment by ruanling** [comment]
> @ruanling what are the specs on your server and how fast is your connection? That seems slow, I can sync all of bsc in 12 hours. How were you able to start the sync in the first place?

I followed the instructions in the documentation, you can see it here [https://docs.dogechain.dog/docs/overview]( https://docs.dogechain.dog/docs/overview),
It only took me 4 hours to run BSC node with NVMe configuration, because BSC has snapshots available, you don't have to waste time to sync

**Comment by kugimiya530** [comment]
Hi dev , we really need snapshot for dogechain

**Comment by null-void-zero** [comment]
> I followed the instructions in the documentation, you can see it here https://docs.dogechain.dog/docs/overview, It only took me 4 hours to run BSC node with NVMe configuration, because BSC has snapshots available, you don't have to waste time to sync
Do you need to set up nodes on 4 different servers? I tried following the instructions but it never started syncing. According to this tweet: https://twitter.com/DogechainFamily/status/1559610340840591360, genesis and node deployment isn't available yet

**Comment by ruanling** [comment]
> > I followed the instructions in the documentation, you can see it here https://docs.dogechain.dog/docs/overview, It only took me 4 hours to run BSC node with NVMe configuration, because BSC has snapshots available, you don't have to waste time to sync
> > Do you need to set up nodes on 4 different servers? I tried following the instructions but it never started syncing. According to this tweet: https://twitter.com/DogechainFamily/status/1559610340840591360, genesis and node deployment isn't available yet

yes, it's still in sync

**Comment by 0xcb9ff9** [comment]
There are some minor problems with the backup function. When the grpc message is too large, the backup will be terminated and the backup file will be deleted. This PR #162  can fix this bug

**Comment by DarianShawn** [comment]
👍🏻  The snapshot repo should be ready to go.

**Comment by DarianShawn** [comment]
Bad news about the current version snapshot backup recovery: It would take minutes to restore every block when height exceeds 800k, which is unacceptable completely.

So the snapshot of the current version is not available.
To make the whole things work, we need to make a big change to the current data structure and provide 'pruning' mechanism. It should be version 2 and not backward compatible.

@abrahamcruise321 @0xcb9ff9 @zivkovicmilos 
Any suggestions are valuable.

**Comment by DarianShawn** [comment]
Use DB instead of block restoration, would save all users' time.

It is provided in the new repo: https://github.com/dogechain-lab/dogechain-snapshots
