### ISSUE TITLE
Cancel transaction

### ISSUE THREAD

**Issue by wi2xner** [dogechain-lab/dogechain#134]
Hello, why is someone trying to withdraw my tokens, I did not make a transaction and found this on the bridge, is it possible to cancel it somehow?
![image](https://user-images.githubusercontent.com/93282600/185001134-26c7d733-a160-4839-88da-67a7c08541c9.png)

**Comment by DarianShawn** [comment]
You could ask it in the  discord channel or official telegram.
By the way, provide more detail would make it faster to be handled.

**Comment by wi2xner** [comment]
I turned and asked for support and I was banned in a telegram, today the same situation happened, money was stolen from me again, help me to cancel this one, please!От: DarianShawnОтправлено: 19 августа 2022 г. в 11:46Кому: dogechain-lab/dogechainКопия: wi2xner; AuthorТема: Re: [dogechain-lab/dogechain] Cancel transaction (Issue #134) You could ask it in the discord channel or official telegram.By the way, provide more detail would make it faster to be handled.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
