### ISSUE TITLE
Golang 1.19 build failed

### ISSUE THREAD

**Issue by 0xcb9ff9** [dogechain-lab/dogechain#143]
### Description

can't  build on golang 1.19

### Your environment

* Fedora Silverblue Linux 36 
* Dogechain v1.1.1
* branch dev 

### Logs

```bash
$ make build
go build -ldflags="-X 'github.com/dogechain-lab/dogechain/versioning.Version=v1.1.1+1928a2a7+2022-08-24_18:56:58'" main.go
# github.com/lucas-clemente/quic-go/internal/qtls
../../../go/pkg/mod/github.com/lucas-clemente/quic-go@v0.25.0/internal/qtls/go119.go:6:13: cannot use "quic-go doesn't build on Go 1.19 yet." (untyped string constant) as int value in variable declaration
```

**Comment by DarianShawn** [comment]
We'd better upgrade `golang` version step by step, so `1.17` would be a nice selection.
You can't tell what would be break when upgrading the compiling tool, especially when there is a long list of dependencies.

**Comment by DarianShawn** [comment]
Close it since we're building in elder golang version.
