### ISSUE TITLE
Ignore broadcasted txs until fully synced

### ISSUE THREAD

**Issue by ircrp** [dogechain-lab/dogechain#156]
When syncing up at certain times you can observe a burst of ```failed to add broadcast tx``` errors being logged which I suppose means that the node is already accepting gossiped transactions and validating them. If possible, we could change this such that subscription to gossiped transactions is initiated once the node is fully synced. This can potentially speed up the sync process

**Comment by DarianShawn** [comment]
Thanks for your advice.
That make sense.
We'll include this feature ASAP.

**Comment by DarianShawn** [comment]
Associated PR #196

**Comment by DarianShawn** [comment]
After a long period of testing, the same problem has not been found for the time being.
