### ISSUE TITLE
{"code":-32600,"message":"txpool is full"}

### ISSUE THREAD

**Issue by past2017** [dogechain-lab/dogechain#160]
version : v1.1.1
when transfer DC, sometimes（5% ratio） error reported " txpool is full"

**Comment by DarianShawn** [comment]
Fixes merged, but not bump version yet. Still in test.

**Comment by DarianShawn** [comment]
@past2017 You could upgrade to the newest version `v1.1.3`, together with the new `genesis.json`.
The newer version had fixed some `txpool` issues. 
We had a `portland` hard fork in `v1.1.2`, so you need to upgrade the `genesis.json`.

**Comment by DarianShawn** [comment]
With more limitation flags and future pruning, not found this issue in full nodes, rpc nodes, and validator nodes.
