### ISSUE TITLE
Please Consider Adding "debug_" to the Dogechain JSON-RPC Namespace

### ISSUE THREAD

**Issue by keennay** [dogechain-lab/dogechain#164]
That is all, thanks.

**Comment by keennay** [comment]
Didn't realize this was already brought up in: https://github.com/dogechain-lab/dogechain/issues/50. Hopefully this adds more visibility.

**Comment by DarianShawn** [comment]
Not done yet.

More focus on `rpc`, `txpool` stability now.
Plan to bring up in the next two milestone or so.

**Comment by DarianShawn** [comment]
Duplicated with #50 .
Would close this, please reply on the previous one.
