### ISSUE TITLE
syncing stops at height of 1981990.

### ISSUE THREAD

**Issue by titbtcqash** [dogechain-lab/dogechain#171]
Hi. I want to run dogechain node,but syncing stops at height of 1981990.
The error is below.
dogechain.consensus.ibft: failed to bulk sync: err="unable to verify block, unable to verify block execution result, invalid block state root"

I used genesis in https://github.com/dogechain-lab/dogechain-docs/blob/main/docs/get-started/full-node-deployment.md　
How to fix this error? Please help.

**Comment by lk479o000** [comment]
I met the same problem

**Comment by DarianShawn** [comment]
There is a hard fork `portland` at height `1981991`.
You need to upgrade your genesis file and node binary version (>= 1.1.2).

**Comment by lk479o000** [comment]
where is new genesis file

> There is a hard fork `portland` at height `1981991`. You need to upgrade your genesis file and node binary version (>= 1.1.2).

Thank you

**Comment by lk479o000** [comment]
> There is a hard fork `portland` at height `1981991`. You need to upgrade your genesis file and node binary version (>= 1.1.2).

Thank you

**Comment by DarianShawn** [comment]
You're welcome.

Close the issue please when you're free to go. 🙌

**Comment by titbtcqash** [comment]
Thanks!  Syncing is successfully completed!
