### ISSUE TITLE
wDOGE transaction problem

### ISSUE THREAD

**Issue by KrzyNow** [dogechain-lab/dogechain#236]
## [Subject of the issue]
I did not receive wDoge on Metamask

### Description
I connected my metamask to https://bridge.dogechain.dog/bridge and sent 111 DOGE.
The transaction is successful but I don't see any wDOGE in the metamask.
Transaction:
2.11.2022, 22:09:10	111.00 Dogecoin	c9fb6112de0b...d1f02f9a  ->	0x901ba4a09b...2952ae81 Complete

### Your environment

* OS and version: Win10
* version of the Dogechain: https://rpc.dogechain.dog
* branch that causes this issue: ?

### Steps to reproduce

* Tell us how to reproduce this issue <br />
* Where the issue is, if you know <br />
* Which commands triggered the issue, if any

### Expected behaviour

111 wDoge written on metamask

### Actual behaviour

I see 0 wDoge in my metamask

### Logs

2.11.2022, 22:09:10	111.00 Dogecoin	c9fb6112de0bf309310b32fd0c3c1d14052cf40659e0891b8b4a799bd1f02f9a  ->	0x901ba4a09b1da749cfe80b8981403bab62c3c3b7b88a55c18fade9362952ae81 Complete

### Proposed solution

If you have an idea of how to fix this issue, please write it down here, so we can begin discussing it: ?

**Comment by KrzyNow** [comment]
wDoge arrived, sorry.

**Comment by DarianShawn** [comment]
Tx issue please go to telegram please.

And sorry for the late arriving (but must arrived) bridging Doge.
We're facing some dust attacks and traffic jam the last few days, so be patient please.

**Comment by KrzyNow** [comment]
Thanks for your answer. I was just afraid that my tx ended up in a "manual correction" area.
Thanks & Greetings
Christoph
