### ISSUE TITLE
RPC endpoint response Content-Type

### ISSUE THREAD

**Issue by czbase** [dogechain-lab/dogechain#247]
### Description

When I send a request to mainnet RPC, it responds with incorrect Content-Type header. It responds with "text/plain" instead of "application/json".

### Expected behaviour

Response Content-Type header should be "application/json"

### Actual behaviour

Response Content-Type header currently is "text/plain"

Mainnet
![image](https://user-images.githubusercontent.com/118026755/201442494-a321323e-3656-4db8-8752-f99d83eb2e67.png)

Testnet
![image](https://user-images.githubusercontent.com/118026755/201442503-f52f22c5-648d-4d45-aa41-5374fc602498.png)

**Comment by DarianShawn** [comment]
Thanks for the head up.
We'll fix it ASAP.

**Comment by czbase** [comment]
thanks, it seems to be fixed already after the recent update, but a new issue with the endpoints popped up. I've created a new issue for that - #255

**Comment by DarianShawn** [comment]
All fixed. Check it out.
