### ISSUE TITLE
RPC endpoint duplicate header - Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by czbase** [dogechain-lab/dogechain#255]
### Description

After the recent mainnet update, the RPC endpoints have started to respond with duplicate HTTP headers. This creates issues especially for Access-Control-Allow-Origin header since the response is then blocked by browser due to CORS policy. Below is a screenshot from browser's developer tools and from postman.

### Expected behaviour

Send Access-Control-Allow-Origin header only once per response

### Actual behaviour

Access-Control-Allow-Origin is sent twice
![image](https://user-images.githubusercontent.com/118026755/201910086-e1c8ec69-704e-4b2b-8506-84f1abee3ce3.png)

Error message from browser's console
![image](https://user-images.githubusercontent.com/118026755/201949515-47db1ace-2d27-432b-b57f-c79a63d72b99.png)

**Comment by DarianShawn** [comment]
All fixed. Check it out.

**Comment by czbase** [comment]
@DarianShawn Looks good now, thank you
