### ISSUE TITLE
Node not syncing

### ISSUE THREAD

**Issue by Baal19** [dogechain-lab/dogechain#266]
### Description

 node is stuck at block 4558059

### Your environment

*Ubuntu 22.04
* v1.2.0

### Logs
```
Nov 30 23:30:54 23m dogechain[1277994]: 2022-11-30T23:30:54.759Z [ERROR] dogechain.consensus.ibft: failed to bulk sync: err="unable to verify block, invalid gas limit, limit = 30877537, want 30000000 +- 29295"
Nov 30 23:30:54 23m dogechain[1277994]: 2022-11-30T23:30:54.759Z [INFO]  dogechain.network: Peer disconnected: id=16Uiu2HAmJKcLRBgpHLpmTdNaaKMCbZ9kv25KNugxVd6Bj3sgDBWT
Nov 30 23:30:54 23m dogechain[1277994]: 2022-11-30T23:30:54.759Z [ERROR] dogechain.consensus.ibft: failed to bulk sync: err="rpc error: code = Unavailable desc = error reading from server: stream reset"
Nov 30 23:30:54 23m dogechain[1277994]: 2022-11-30T23:30:54.759Z [ERROR] dogechain.consensus.ibft: failed to bulk sync: err="rpc error: code = Canceled desc = grpc: the client connection is closing"
Nov 30 23:31:00 23m
```

**Comment by DarianShawn** [comment]
It should not be. Provide more information to help us diagnose, please.

Here's a quick bandage for you:
**SET** server command flag `--seal=false` or leave it blank.
**DO NOT** set server command flag `--block-gas-target`, leave it to the active sealer.

**Comment by Baal19** [comment]
> It should not be. Provide more information to help us diagnose, please.
> 
> Here's a quick bandage for you: **SET** server command flag `--seal=false` or leave it blank. **DO NOT** set server command flag `--block-gas-target`, leave it to the active sealer.

Thank you, I had already the seal flag set to false. This is my execstart command

```
ExecStart=dogechain server \
    --data-dir=/data6/dogechain/data \
    --chain=/data6/dogechain/genesis.json/mainnet-genesis.json \
    --seal=false \
    --libp2p=0.0.0.0:1478 \
    --jsonrpc=0.0.0.0:11568 \
    --max-inbound-peers=128 \
    --max-outbound-peers=16
```
Which additional information do you need?

**Comment by DarianShawn** [comment]
You can reduce the inbound and outbound peers to a reasonable number. Or leave it blank to use the default.

In addition, v1.2.1 is released, a new version of the `syncer` protocol, which is faster and consumes less bandwidth.
We recommend that you upgrade it.

**Comment by DarianShawn** [comment]
Close it due to long inactivation.
