### ISSUE TITLE
Clear timeout pending transactions of txpool

### ISSUE THREAD

**Issue by DarianShawn** [dogechain-lab/dogechain#33]
I think it better to fork the `go-ethereum` implementation of clearing those pending transactions which waited too long to be packed. The default value could be set `1 hour`.

Currently, the pending transactions would not removed even when it's overflow.
To handle the `DoS attack`, we might have some ways, each has its pros and cons:

1. Remove future transactions.
2. Keep it simple, enlarge the txpool slots. Do nothing in `AddTx` when txpool overflow, but would only keep the pending transactions for 1 hour (by default).
3. Distinguish the `local` and `gossip` transaction, use different pool queues to store, reject and remove gossip txs when txpool overflow, accept local tx anyway. Add some punishment to the largest account queue periodically just like `go-ethereum`.

The 1st one is quite straight forward, but it will make some normal user difficult to send transactions when the network is congested.
The 2nd one is much more clever, and this proposal is about to describe it.
The 3rd one would be the most complicated, hard to implement, hard to test, which might bring a buggy implementation.

**Comment by DarianShawn** [comment]
@abrahamcruise321 @zivkovicmilos 
Isn't it a valuable issue for more discussion?
I've tried the 1st solution in [this branch](https://github.com/dogechain-lab/jury/tree/feature/drop-not-promoted-transactions), it seems not working fine as I expected.
Reviewing the purpose of reducing the security risk, I came out the previous 3 ways, but a little confused on it now.
Is there any more elegant solution on it?

**Comment by zivkovicmilos** [comment]
Hey @DarianShawn,

We already have a TxPool pruning implementation in the works on Edge:
https://github.com/0xPolygon/polygon-edge/pull/541

**Comment by DarianShawn** [comment]
> Hey @DarianShawn,
> 
> We already have a TxPool pruning implementation in the works on Edge: [0xPolygon#541](https://github.com/0xPolygon/polygon-edge/pull/541)

Thanks. The feature is awesome.
The `Demote()` would do great help of reducing the thread of DoS attack.
I'll keep an eye on this PR.

**Comment by DarianShawn** [comment]
Already done with #105 .
