### ISSUE TITLE
Dogechain Client

### ISSUE THREAD

**Issue by Ranofty** [dogechain-lab/dogechain#347]
### Description

Describe your issue in as much detail as possible here

### Your environment

* OS and version
* version of the Dogechain
* branch that causes this issue

### Steps to reproduce

Hello, good day! Could you please tell me which client Dogechain uses?

**Comment by 0xcb9ff9** [comment]
General user: use the Ethereum-compatible wallet client (like [MetaMask](https://github.com/MetaMask) )
DApp developers: use [web3.js (JavaScript)](https://github.com/web3/web3.js), [web3.py (Python)](https://github.com/ethereum/web3.py)

**Comment by DarianShawn** [comment]
Done and inactive for a long time, close it.
