### ISSUE TITLE
Not able to find my transaction on public RPC or Explorer

### ISSUE THREAD

**Issue by sjadiya-supra** [dogechain-lab/dogechain#358]
Hello Dogechain Team

I'd synced my two fullnodes with Dogechain mainnet, and did successful transaction over the dogechain mainnet as well through them, but when I am trying to fetch transaction over the Dogechain explorer with transaction hash, I am not able to find any details about them. 

Here attaching the CURL calls for the transactions with their respective fullnode RPCs, Please check it out and guide me to resolve it. 

```
curl --location 'http://my_node_IP_1:8545/' \
--header 'Content-Type: application/json' \
--data '{
  "jsonrpc": "2.0",
  "id": 0,
  "method": "eth_getTransactionByHash",
  "params": ["0x303ac1877cee55358016b21e789e754a7bcb531236ef98da58598dd5163de511"]
}'
```

```
curl --location 'http://my_node_ip_2:8545/' \
--header 'Content-Type: application/json' \
--data '{
  "jsonrpc": "2.0",
  "id": 0,
  "method": "eth_getTransactionByHash",
  "params": ["0x842ab7c42fb9a3b4680d4f2ec6789bfed38d19a58c4f03263c06f3ca791b5636"]
}'
```

![image](https://github.com/dogechain-lab/dogechain/assets/90824946/b4523151-a660-40f5-a303-1f423156ea2e)

**Comment by sjadiya-supra** [comment]
@DarianShawn can you please help me out?

**Comment by masayil** [comment]
For some reason your transaction has not been confirmed by validators.
```
{"jsonrpc":"2.0","id":0,"result":{"nonce":"0x0","gasPrice":"0xba43b7400","gas":"0x112a880","to":"0x4077cc6727DD4C4eE0fdc3dF0f6F00a470E78e5C","value":"0x0","input":"0xf2221ce30000000000000000000000000000000000000000000000000000000000000001a77657e4a101217193a6f01a8ebed02afab70688483b138a8ed642c79672fc1c0000000000000000000000000000000000000000000000000000000000000160174c00ee1e335184e8dae4f3b4a59e06255312ae23df81257fb410e253408e431093cafdfd6f8d53b6ff6acfdc4e1f3ded5877d7199b2d88eeb8d1d35f11860600000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e3dc7887304380cfc480fcdf6042362e0223037b00000000000000000000000000000000000000000000000000000000000001a0000000000000000000000000d2c16892048a64ee27b926d2b3b534a31868b65000000000000000000000000000000000000000000000000000388f9c432588000000000000000000000000000000000000000000000000000000000000000020a6030b0085e7232472c101edc776426e15199000703f842842da8cc01a2e70e8000000000000000000000000000000000000000000000000000000000000001d646973747269627574652875696e743235362c75696e743235365b5d29000000","v":"0xfc3","r":"0x50c4fbb43e5d2d0bb36a89bf11dcf40546028372e22c78fe78888a31a616f41f","s":"0x5ea9650a7921e9a0afbd7db7987d32be7956689b640181a9167277dea34feab0","hash":"0x303ac1877cee55358016b21e789e754a7bcb531236ef98da58598dd5163de511","from":"0x301A0EC9182A59716925c6800D90E9E4e218F005","blockHash":null,"blockNumber":null,"transactionIndex":null}}
```
**blockHash":null,"blockNumber":null,"transactionIndex":null**

**Comment by masayil** [comment]
1. Please increase the gas price.  Too low  , at least >= **250**GWEI
```
 curl --location 'https://rpc.ankr.com/dogechain' --header 'Content-Type: application/json' --data '{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "eth_gasPrice",
  "params": []
}'
{"jsonrpc":"2.0","id":1,"result":"0x3a35294400"}
```
In your transaction, gasPrice is set to 0xba43b7400
2. **IMPORTANT** Please do not  expose the private node ip you own in the repo.
@sjadiya-supra

**Comment by sjadiya-supra** [comment]
@masayil how can I set gas_price on Fullnode binary?

**Comment by masayil** [comment]
1. **--price-limit=250000000000** Currently the minimum gasPrice allowed by Dogchain is 250GWEI. This parameter can prevent nodes from accepting transactions whose gasprice is less than 250GWEI.
2. Using txpool_content, you can see that the transaction is pending in the node tx pool

**Comment by DarianShawn** [comment]
> 1. **--price-limit=250000000000** Currently the minimum gasPrice allowed by Dogchain is 250GWEI. This parameter can prevent nodes from accepting transactions whose gasprice is less than 250GWEI.
> 2. Using txpool_content, you can see that the transaction is pending in the node tx pool

Thanks for the quick response @masayil.

@sjadiya-supra 
We do increase the gas price limit to 250 GWei, to prevent dust attacks happened on the Mainnet.
The default gas price limit is 50 GWei, so I guess that is why your full nodes didn't reply the correct gas price.
Your issue reminds us that the default configuration values need to be updated to avoid confusion.

**Comment by sjadiya-supra** [comment]
@DarianShawn okay, so do I have to do any configuration related changes on the fullnode side and restart the binary again?

**Comment by DarianShawn** [comment]
> @DarianShawn okay, so do I have to do any configuration related changes on the fullnode side and restart the binary again?

`--price-limit=250000000000` is enough for the issue.

**Comment by sjadiya-supra** [comment]
okay, applied and Now I can see the price-limit to 250 GWei, thanks for the quick response guys. really appreciated.
