### ISSUE TITLE
dogechain.network.keep_available: all peers add to dial queue, no random peer to dial

### ISSUE THREAD

**Issue by Supra-RaghulRajeshR** [dogechain-lab/dogechain#360]
Hello my testnet fullnode dogechain suddenly stopped working and showing like `dogechain.network.keep_available: all peers add to dial queue, no random peer to dial` i have v1.2.4,. can any one help me out with it?

**Comment by DarianShawn** [comment]
Sorry the late response.
We just move on the the new client, new consensus and new hard fork -- Hawaii.

Check this out for more information.
https://docs.dogechain.dog/docs/get-started/hawaii-hard-fork

The new client repo is here.
https://github.com/dogechain-lab/dbsc

**Comment by DarianShawn** [comment]
The Testnet is redeployed and upgraded to Hawaii Hard fork.
That's the reason why you lost all connections. Sorry about that.

You need to reboot your nodes with new client and new `genesis.json`. We'll provide it ASAP.

**Comment by Supra-RaghulRajeshR** [comment]
Hello @DarianShawn thanks for the response. do i need to remove the current binaries and install all the things followed by this document? https://docs.dogechain.dog/docs/get-started/hawaii-hard-fork.

**Comment by Supra-RaghulRajeshR** [comment]
This config.toml is not available inside the mainner.zip;  can you pls tell me where can i find it?
@DarianShawn

**Comment by Supra-RaghulRajeshR** [comment]
i have followed the blog and changed my mainnet node one it is facing `looking for peers` error.

` is stalling: withheld skeleton headers: advertised 19069275, withheld #18421287"
Nov 03 06:35:35 dogechain-mainnet-node1-2 geth[2282956]: INFO [11-03|06:35:35.072] Looking for peers                        peercount=1 tried=98 static=0
Nov 03 06:35:35 dogechain-mainnet-node1-2 geth[2282956]: WARN [11-03|06:35:35.989] Peer withheld skeleton headers           peer=74e1bd31 advertised=19,069,280 withheld=18,421,287
Nov 03 06:35:35 dogechain-mainnet-node1-2 geth[2282956]: WARN [11-03|06:35:35.989] Synchronisation failed, dropping peer    peer=74e1bd314148d9c396216a5adbbd5050ad8569a2c0c13c972ed023d23d0d63b2 err="peer is stalling: withheld skeleton headers: advertised 19069280, withheld #18421287"
Nov 03 06:35:45 dogechain-mainnet-node1-2 geth[2282956]: INFO [11-03|06:35:45.673] Looking for peers                        peercount=0 tried=156 static=0
Nov 03 06:35:50 dogechain-mainnet-node1-2 geth[2282956]: WARN [11-03|06:35:50.030] Snapshot extension registration failed   peer=48ec84b2 err="peer connected on snap without compatible eth support"
Nov 03 06:35:55 dogechain-mainnet-node1-2 geth[2282956]: WARN [11-03|06:35:55.349] Peer withheld skeleton headers           peer=17b7eeff advertised=19,069,290 withheld=18,421,287
Nov 03 06:35:55 dogechain-mainnet-node1-2 geth[2282956]: WARN [11-03|06:35:55.349] Synchronisation failed, dropping peer    peer=17b7eeffef54725388ff6f0cbcedc51705c745c4e01b71b8388f58cd3a468b57 err="peer is stalling: withheld skeleton headers: advertised 19069290, withheld #18421287"
Nov 03 06:35:55 dogechain-mainnet-node1-2 geth[2282956]: INFO [11-03|06:35:55.675] Looking for peers                        peercount=0 tried=133 static=0
Nov 03 06:35:58 dogechain-mainnet-node1-2 geth[2282956]: WARN [11-03|06:35:58.311] Snapshot extension registration failed   peer=05cbd310 err="peer connected on snap without compatible eth support"
Nov 03 06:36:05 dogechain-mainnet-node1-2 geth[2282956]: INFO [11-03|06:36:05.681] Looking for peers                        peercount=1 tried=98  static=0
Nov 03 06:36:15 dogechain-mainnet-node1-2 geth[2282956]: INFO [11-03|06:36:15.682] Looking for peers                        peercount=0 tried=201 static=0
`
