### ISSUE TITLE
add debug_traceTransaction feature.

### ISSUE THREAD

**Issue by abrahamcruise321** [dogechain-lab/dogechain#50]
https://geth.ethereum.org/docs/rpc/ns-debug#debug_tracechain

**debug_traceTransaction**
The traceTransaction debugging method will attempt to run the transaction in the exact same manner as it was executed on the network. It will replay any transaction that may have been executed prior to this one before it will finally attempt to execute the transaction that corresponds to the given hash.

In addition to the hash of the transaction you may give it a secondary optional argument, which specifies the options for this specific call. The possible options are:

disableStorage: BOOL. Setting this to true will disable storage capture (default = false).
disableStack: BOOL. Setting this to true will disable stack capture (default = false).
enableMemory: BOOL. Setting this to true will enable memory capture (default = false).
enableReturnData: BOOL. Setting this to true will enable return data capture (default = false).
tracer: STRING. Setting this will enable JavaScript-based transaction tracing, described below. If set, the previous four arguments will be ignored.
timeout: STRING. Overrides the default timeout of 5 seconds for JavaScript-based tracing calls. Valid values are described [here](https://golang.org/pkg/time/#ParseDuration).

**Comment by keennay** [comment]
Yes please!

**Comment by DarianShawn** [comment]
The branch `feature/debug-rpc-endpoint` is under development.

**Comment by DarianShawn** [comment]
The basic `debug_traceTransaction` feature is merged and tested.
Compares transactions in Dogechain devnet and Ethereum Goerli network:

|              Usage              |                       Dogechain devnet                       |                       Ethereum Goerli                        |
| :-----------------------------: | :----------------------------------------------------------: | :----------------------------------------------------------: |
|         Create Contract         | 0x522457f0852ab3dd43d6063d2d23c76ef1f2f6ecd52eadc02b7fe807b503955e | 0x8288e69af9e1baea5ff425e95958f46a8bca156d1af4787103a3d712b3333f8c |
|           Call Method           | 0x9285a1c1236e835fb5564407e6f590a3254c3487a51c51285b47b03076235d9c | 0xe398d167f2790124b7a4fa325e9396832132c8a9b9f0d8675cafb9c4d57fc1d8 |
|         Create Contract         | 0x805a8416c90c95cdb9be8a46f34ac0bf70a1556c929e764bfcc46cdf3d835d93 | 0xe5d891da71bde8787691ad66173227c343943d5363e1e9d88aa9cc1c50a4a9d8 |
| Create Contract With  Parameter | 0xd45540d2befaf278be80d8c6d1b1241a084127947f29431b2f541a9cdf8f8a0c | 0x9d1d996c6a920b5fa1291b2b6bf493bbc632d3a263c187d767e00fbf89f2776a |
|              Call               | 0x5af91ff80b1c0023c1540d37ff8be92ecce53e4394a3fd05acabfbf262162e18 | 0x930be9a14f70845cb91a190c5a815ab4637b6146aa46b3e819fb729b0c9356cd |
|          Delegate Call          | 0x90e992e32d6ef6e6f046bca1b8656f0cb217b42e498187367fa67326d2ff1c02 | 0xbed434344f9fd68f4cc2111d82ca09d67c0c63f117acf1346312acb3184298b6 |
|         Create Contract         | 0xc6219aa16807ae6172edf4f6021b101eee056eb314328e19899ff7fcfb9bcefc | 0xbdf27ec28368df84e1b58959d18fbdd47c585a8788d528a0e3d580ae5c2da202 |
|       Revert With Message       | 0xf35b8ad4ef2b2b899cbb622f835dd7169dcf6bc0990d635b0c844e5d0d23ec38 | 0x3cd7cd39be4d007c1f43e38014b22a80ba799bfc88f4856f92e0de5cb09be970 |
|     Revert Without Message      | 0xfbd042894a240f265a54a63946995c81e38a57f1290bf5068d6d7872d8c7c30d | 0xb90cb3726fa7249d7cdf54f1e66d102efb02860a2c45745f119db4fcd21e782e |

The responses are nearly equal, except for a small difference in gas consumption.

**Comment by Thorsson** [comment]
@DarianShawn has this been already released to Mainnet?

**Comment by keennay** [comment]
Hi, are there any plans to add callTracer? Thanks

**Comment by DarianShawn** [comment]
> @DarianShawn has this been already released to Mainnet?

The official MainNet RPC would not enable `WebSocket`, `GraphQL`, and `debug` namespace endpoints would not be enabled, too. Due to performance consuming.

**Comment by DarianShawn** [comment]
> Hi, are there any plans to add callTracer? Thanks

Not yet. Any PR is welcome.

**Comment by keennay** [comment]
> > Hi, are there any plans to add callTracer? Thanks
> 
> Not yet. Any PR is welcome.

Hey, hope all is well. Are there any plans / ETA to add callTracer? Thanks

**Comment by DarianShawn** [comment]
Not yet, sorry about that.
Still working on snapshot features.
And database pruning is more urgent due to larger scale storage.
